Repository ghifarit53/daycula-vim, pull requests merged in 2020-10, with the labels that each got.

#1 add colorscheme
  README.md
  colors/daycula.vim
Labels: hacktoberfest-accepted

#2 add lightline theme
  autoload/lightline/colorscheme/daycula.vim
Labels: hacktoberfest-accepted

#3 add airline theme
  autoload/airline/themes/daycula.vim
Labels: hacktoberfest-accepted

#6 add ports for some terminal emulators
  ports/daycula.Xresources
  ports/daycula.conf
  ports/daycula.yaml
Labels: enhancement, hacktoberfest-accepted

#9 Added iTerm2 port
  ports/Daycula.itermcolors
Labels: enhancement, hacktoberfest-accepted

#7 Documentation in help format
  README.md
  doc/daycula.txt
Labels: documentation, hacktoberfest-accepted
